### ISSUE TITLE
Not able to activate plugin in Wordpress Multisite environment

### ISSUE THREAD

**Issue by jbrabants** [ibericode/scroll-triggered-boxes#23]
The plugin doesn't activate in our multisite environment.

When I click Network Activate, it stays inactive, when I go to a site to activate it there, it doesn't get activated either.

**Comment by dannyvankooten** [comment]
Hi @jbrabants, is this using WordPress 4.3 and the latest version of the plugin?

**Comment by dannyvankooten** [comment]
Hey @jbrabants ,

We've released version 2.1.1 of the plugin yesterday in which this issue should be fixed. Can you confirm please?

Thanks a lot!

**Comment by jbrabants** [comment]
Hi @dannyvankooten , 

will give it another try today. Does it integrate with MailChimp?

**Comment by dannyvankooten** [comment]
Hey @jbrabants,

Yes, definitely. You can use our (free) [MailChimp for WordPress](https://mc4wp.com/) plugin for that. It has a paid version as well but the free version should suffice if you want to show a form in your box. You can do just that by using the following shortcode as the box content.

```
[mc4wp_form]
```

**Comment by jbrabants** [comment]
Thanks, 

works but looks ugly as hell :) is it possible to provide the css for the examples you show on the plugin page on wordpress.org? 

The box doesn't show sign up button next to e-mail field, it keeps below the field after I changed Mailchimp settings, also it doesn't use my primary and accent color which I've selected and doesn't use my max width that I have filled in in settings.

**Comment by dannyvankooten** [comment]
Hey @jbrabants,

Got an URL so I can take a look? Most likely, your theme is interfering with some of the plugin styling. Also, what MailChimp setting are you using to have the field appear inline (next to the button) instead of on a new line / below the field.

This KB article should be able to help you with inlining your form: https://mc4wp.com/kb/single-line-forms/

Anyway, let me know and I'll provide you with a CSS snippet that should be of help. :-)

**Comment by jbrabants** [comment]
Here's a preview: http://blog.xpenditure.com/es/ 
if you scroll down ;) the box appears....

**Comment by jbrabants** [comment]
went through the article, do I have to upgrade to be able to use the CSS Styles Builder?

**Comment by jbrabants** [comment]
Hi, do you still think about the CSS snippets for better styling? ;)

**Comment by dannyvankooten** [comment]
Hey Joris,

Definitely, sorry for the delay in my reply. Had a crazy busy day this
Friday. Can you please send an email where you link to this topic to
*support@mc4wp.com
<support@mc4wp.com>* or *support@scrolltriggeredboxes.com
<support@scrolltriggeredboxes.com> *?

That way, my team will get to see your email as well which will help in
getting a faster reply. :-)

--
Danny van Kooten
dannyvankooten.com

2015-08-28 19:30 GMT+07:00 Joris <notifications@github.com>:
