### ISSUE TITLE
Auto-close when integrating MC4WP

### ISSUE THREAD

**Issue by iMazed** [ibericode/scroll-triggered-boxes#26]
When integrating MC4WP (I've tested with Lite so far), the form responds after submitting only displays when scrolling down again so the STB box appears. This might cause confusion. The AJAX feature in Pro should resolve this, but it's an issue for Lite users. 

A ticket has already been opened on this: https://wordpress.org/support/topic/prevent-box-from-auto-closing-after-form-submission?replies=2

**Comment by dannyvankooten** [comment]
Related #30
